version: "3.8"

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver2019
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "sqlcoNgoc4@"
            ACCEPT_EULA: "Y"
        volumes:
            - sql_data:/var/opt/mssql

    backend:
        build: ./backend
        container_name: springboot-app
        restart: always
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=eCommerceNghienDT;encrypt=true;trustServerCertificate=true;"
            SPRING_DATASOURCE_USERNAME: "sa"
            SPRING_DATASOURCE_PASSWORD: "sqlcoNgoc4@"
        depends_on:
            - sqlserver

    frontend:
        build: ./frontend
        container_name: angular-app
        restart: always
        ports:
            - "8081:80"
volumes:
    sql_data:
